// Copyright 2026 bleighk. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press).
//
// Custom local-table migration: game_backlog.
//
// Table game_backlog holds the user's personal game backlog — one row per
// RAWG game id, mirroring the rawg_id/title/slug identity used by the live
// commands and adding local play-tracking state that RAWG does not model:
//   - status      backlog | in-progress | finished | dropped
//   - hours       hours played (local, RAWG has no per-user playtime)
//   - added_at    RFC3339 UTC timestamp when the row was first added
//                 (never rewritten by upserts — the age drives the queue's
//                 longest-waiting tier and the already-present notice)
//   - finished_at RFC3339 UTC set when status first flips to finished,
//                 cleared when the row leaves finished
//   - user_rating RAWG-style 1-5 rating the user assigns after finishing
//   - notes       free-form local notes
//
// Migration is idempotent (CREATE TABLE/INDEX IF NOT EXISTS) and runs from
// migrateExtras, so every read-write store open converges to the same schema.

package store

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
)

// Backlog row statuses.
const (
	GameBacklogStatusBacklog    = "backlog"
	GameBacklogStatusInProgress = "in-progress"
	GameBacklogStatusFinished   = "finished"
	GameBacklogStatusDropped    = "dropped"
)

// gameBacklogTimeFormat is the RFC3339 UTC layout stamped into added_at and
// finished_at. Fixed-width and lexicographically sortable, so ORDER BY on
// the text columns is chronological.
const gameBacklogTimeFormat = time.RFC3339

// ValidGameBacklogStatus reports whether s is one of the four backlog statuses.
func ValidGameBacklogStatus(s string) bool {
	switch s {
	case GameBacklogStatusBacklog, GameBacklogStatusInProgress,
		GameBacklogStatusFinished, GameBacklogStatusDropped:
		return true
	}
	return false
}

// GameBacklogRow is one stored backlog entry.
type GameBacklogRow struct {
	RawgID     int     `json:"rawg_id"`
	Title      string  `json:"title"`
	Slug       string  `json:"slug"`
	AddedAt    string  `json:"added_at"`
	Status     string  `json:"status"`
	Hours      float64 `json:"hours"`
	FinishedAt string  `json:"finished_at"`
	UserRating float64 `json:"user_rating"`
	Notes      string  `json:"notes"`
}

// GameBacklogInput carries the fields a caller can set on add/update.
// RawgID and Title are required; AddedAt/FinishedAt are computed here.
type GameBacklogInput struct {
	RawgID     int
	Title      string
	Slug       string
	Status     string
	Hours      float64
	UserRating float64
	Notes      string
}

// migrateGameBacklog creates the game_backlog table and its indexes. Called
// from migrateExtras on every read-write store open; safe to re-run.
func (s *Store) migrateGameBacklog(ctx context.Context, conn *sql.Conn) error {
	if _, err := conn.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS game_backlog (
		rawg_id     INTEGER PRIMARY KEY,
		title       TEXT NOT NULL,
		slug        TEXT NOT NULL DEFAULT '',
		added_at    TEXT NOT NULL,
		status      TEXT NOT NULL DEFAULT 'backlog',
		hours       REAL NOT NULL DEFAULT 0,
		finished_at TEXT NOT NULL DEFAULT '',
		user_rating REAL NOT NULL DEFAULT 0,
		notes       TEXT NOT NULL DEFAULT ''
	)`); err != nil {
		return fmt.Errorf("game_backlog table migration failed: %w", err)
	}
	if _, err := conn.ExecContext(ctx, `CREATE INDEX IF NOT EXISTS idx_game_backlog_status ON game_backlog(status)`); err != nil {
		return fmt.Errorf("game_backlog status index migration failed: %w", err)
	}
	if _, err := conn.ExecContext(ctx, `CREATE INDEX IF NOT EXISTS idx_game_backlog_added_at ON game_backlog(added_at)`); err != nil {
		return fmt.Errorf("game_backlog added_at index migration failed: %w", err)
	}
	return nil
}

const gameBacklogSelectColumns = `SELECT rawg_id, title, slug, added_at, status, hours, finished_at, user_rating, notes FROM game_backlog`

func scanGameBacklogRow(row interface{ Scan(dest ...any) error }) (GameBacklogRow, error) {
	var r GameBacklogRow
	if err := row.Scan(&r.RawgID, &r.Title, &r.Slug, &r.AddedAt, &r.Status,
		&r.Hours, &r.FinishedAt, &r.UserRating, &r.Notes); err != nil {
		return GameBacklogRow{}, err
	}
	return r, nil
}

// GetGameBacklog returns the row for rawgID, or (GameBacklogRow{}, false, nil)
// when the game is not on the backlog.
func (s *Store) GetGameBacklog(ctx context.Context, rawgID int) (GameBacklogRow, bool, error) {
	row, err := scanGameBacklogRow(s.db.QueryRowContext(ctx,
		gameBacklogSelectColumns+` WHERE rawg_id = ?`, rawgID))
	if err == sql.ErrNoRows {
		return GameBacklogRow{}, false, nil
	}
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("get game_backlog row: %w", err)
	}
	return row, true, nil
}

// FindGameBacklogByTitle returns exact (case-insensitive) title matches,
// most recently added first.
func (s *Store) FindGameBacklogByTitle(ctx context.Context, title string) ([]GameBacklogRow, error) {
	rows, err := s.db.QueryContext(ctx,
		gameBacklogSelectColumns+` WHERE lower(title) = lower(?) ORDER BY added_at DESC`,
		strings.TrimSpace(title))
	if err != nil {
		return nil, fmt.Errorf("find game_backlog by title: %w", err)
	}
	defer rows.Close()
	out := []GameBacklogRow{}
	for rows.Next() {
		r, err := scanGameBacklogRow(rows)
		if err != nil {
			return nil, fmt.Errorf("scan game_backlog row: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// gameBacklogFinishedAt reconciles finished_at for a status transition:
// entering finished stamps now, leaving finished clears, anything else
// preserves the existing timestamp.
func gameBacklogFinishedAt(oldStatus, newStatus, oldFinishedAt string) string {
	if newStatus == GameBacklogStatusFinished && oldStatus != GameBacklogStatusFinished {
		return time.Now().UTC().Format(gameBacklogTimeFormat)
	}
	if newStatus != GameBacklogStatusFinished && oldStatus == GameBacklogStatusFinished {
		return ""
	}
	return oldFinishedAt
}

// UpsertGameBacklog inserts a new row or, when rawgID already exists, updates
// title/slug/status/hours/user_rating/notes in place — added_at is preserved
// and finished_at follows the status transition rules. Returns the stored row
// and whether this call inserted it (false = existing row was updated).
//
// The write is guarded by the single-writer lock and executed in one
// transaction (SELECT + INSERT/UPDATE) so a status flip can never lose its
// finished_at stamp.
func (s *Store) UpsertGameBacklog(ctx context.Context, in GameBacklogInput) (GameBacklogRow, bool, error) {
	if in.RawgID <= 0 {
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: rawg_id is required")
	}
	if strings.TrimSpace(in.Title) == "" {
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: title is required")
	}
	if in.Status == "" {
		in.Status = GameBacklogStatusBacklog
	}
	if !ValidGameBacklogStatus(in.Status) {
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: unknown status %q", in.Status)
	}
	if in.Hours < 0 {
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: hours cannot be negative")
	}
	if in.UserRating < 0 || in.UserRating > 5 {
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: user_rating must be between 0 and 5")
	}

	s.lockForWrite()
	defer s.unlockAfterWrite()

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: %w", err)
	}
	defer tx.Rollback()

	var inserted bool
	var row GameBacklogRow
	existing, err := scanGameBacklogRow(tx.QueryRowContext(ctx,
		gameBacklogSelectColumns+` WHERE rawg_id = ?`, in.RawgID))
	switch {
	case err == sql.ErrNoRows:
		now := time.Now().UTC().Format(gameBacklogTimeFormat)
		finishedAt := gameBacklogFinishedAt("", in.Status, "")
		if _, err := tx.ExecContext(ctx, `INSERT INTO game_backlog
			(rawg_id, title, slug, added_at, status, hours, finished_at, user_rating, notes)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
			in.RawgID, in.Title, in.Slug, now, in.Status, in.Hours, finishedAt, in.UserRating, in.Notes); err != nil {
			return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: %w", err)
		}
		row = GameBacklogRow{
			RawgID: in.RawgID, Title: in.Title, Slug: in.Slug, AddedAt: now,
			Status: in.Status, Hours: in.Hours, FinishedAt: finishedAt,
			UserRating: in.UserRating, Notes: in.Notes,
		}
		inserted = true
	case err != nil:
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: %w", err)
	default:
		finishedAt := gameBacklogFinishedAt(existing.Status, in.Status, existing.FinishedAt)
		if _, err := tx.ExecContext(ctx, `UPDATE game_backlog SET
			title = ?, slug = ?, status = ?, hours = ?, finished_at = ?, user_rating = ?, notes = ?
			WHERE rawg_id = ?`,
			in.Title, in.Slug, in.Status, in.Hours, finishedAt, in.UserRating, in.Notes, in.RawgID); err != nil {
			return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: %w", err)
		}
		row = existing
		row.Title, row.Slug, row.Status = in.Title, in.Slug, in.Status
		row.Hours, row.UserRating, row.Notes = in.Hours, in.UserRating, in.Notes
		row.FinishedAt = finishedAt
	}

	if err := tx.Commit(); err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("upsert game_backlog: %w", err)
	}
	return row, inserted, nil
}

// SetGameBacklogStatus flips a row's status and reconciles finished_at
// (stamped on entering finished, cleared on leaving it). Returns the updated
// row, or ok=false when rawgID is not on the backlog.
func (s *Store) SetGameBacklogStatus(ctx context.Context, rawgID int, status string) (GameBacklogRow, bool, error) {
	if !ValidGameBacklogStatus(status) {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog status: unknown status %q", status)
	}

	s.lockForWrite()
	defer s.unlockAfterWrite()

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog status: %w", err)
	}
	defer tx.Rollback()

	existing, err := scanGameBacklogRow(tx.QueryRowContext(ctx,
		gameBacklogSelectColumns+` WHERE rawg_id = ?`, rawgID))
	if err == sql.ErrNoRows {
		return GameBacklogRow{}, false, nil
	}
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog status: %w", err)
	}
	finishedAt := gameBacklogFinishedAt(existing.Status, status, existing.FinishedAt)
	if _, err := tx.ExecContext(ctx,
		`UPDATE game_backlog SET status = ?, finished_at = ? WHERE rawg_id = ?`,
		status, finishedAt, rawgID); err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog status: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog status: %w", err)
	}
	existing.Status = status
	existing.FinishedAt = finishedAt
	return existing, true, nil
}

// SetGameBacklogHours updates hours played. Returns ok=false when rawgID is
// not on the backlog.
func (s *Store) SetGameBacklogHours(ctx context.Context, rawgID int, hours float64) (GameBacklogRow, bool, error) {
	if hours < 0 {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog hours: hours cannot be negative")
	}

	s.lockForWrite()
	defer s.unlockAfterWrite()

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog hours: %w", err)
	}
	defer tx.Rollback()

	existing, err := scanGameBacklogRow(tx.QueryRowContext(ctx,
		gameBacklogSelectColumns+` WHERE rawg_id = ?`, rawgID))
	if err == sql.ErrNoRows {
		return GameBacklogRow{}, false, nil
	}
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog hours: %w", err)
	}
	if _, err := tx.ExecContext(ctx,
		`UPDATE game_backlog SET hours = ? WHERE rawg_id = ?`, hours, rawgID); err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog hours: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("set game_backlog hours: %w", err)
	}
	existing.Hours = hours
	return existing, true, nil
}

// RemoveGameBacklog deletes a row by RAWG id, returning the removed row and
// whether anything was deleted.
func (s *Store) RemoveGameBacklog(ctx context.Context, rawgID int) (GameBacklogRow, bool, error) {
	s.lockForWrite()
	defer s.unlockAfterWrite()

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("remove game_backlog: %w", err)
	}
	defer tx.Rollback()

	existing, err := scanGameBacklogRow(tx.QueryRowContext(ctx,
		gameBacklogSelectColumns+` WHERE rawg_id = ?`, rawgID))
	if err == sql.ErrNoRows {
		return GameBacklogRow{}, false, nil
	}
	if err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("remove game_backlog: %w", err)
	}
	if _, err := tx.ExecContext(ctx, `DELETE FROM game_backlog WHERE rawg_id = ?`, rawgID); err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("remove game_backlog: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return GameBacklogRow{}, false, fmt.Errorf("remove game_backlog: %w", err)
	}
	return existing, true, nil
}

// ListGameBacklogFilter bounds ListGameBacklog: optional exact status filter,
// sort key (added|title|hours), and a row cap (defaults when unset).
type ListGameBacklogFilter struct {
	Status string
	Sort   string
	Limit  int
}

const defaultGameBacklogListLimit = 500

// gameBacklogSortOrder whitelists sort keys to ORDER BY fragments; the input
// never reaches SQL otherwise.
func gameBacklogSortOrder(sort string) string {
	switch sort {
	case "title":
		return ` ORDER BY title COLLATE NOCASE ASC`
	case "hours":
		return ` ORDER BY hours DESC, added_at DESC`
	default: // "added"
		return ` ORDER BY added_at DESC`
	}
}

// ListGameBacklog returns rows per the filter. An empty result is a valid
// state ([]GameBacklogRow{}, nil), never nil.
func (s *Store) ListGameBacklog(ctx context.Context, f ListGameBacklogFilter) ([]GameBacklogRow, error) {
	if f.Status != "" && !ValidGameBacklogStatus(f.Status) {
		return nil, fmt.Errorf("list game_backlog: unknown status %q", f.Status)
	}
	limit := f.Limit
	if limit <= 0 {
		limit = defaultGameBacklogListLimit
	}

	query := gameBacklogSelectColumns + ` WHERE 1=1`
	var args []any
	if f.Status != "" {
		query += ` AND status = ?`
		args = append(args, f.Status)
	}
	query += gameBacklogSortOrder(f.Sort) + ` LIMIT ?`
	args = append(args, limit)

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("list game_backlog: %w", err)
	}
	defer rows.Close()
	out := []GameBacklogRow{}
	for rows.Next() {
		r, err := scanGameBacklogRow(rows)
		if err != nil {
			return nil, fmt.Errorf("scan game_backlog row: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// SearchGameBacklog returns rows whose title, slug, or notes contain query
// (case-insensitive substring), ranked title > slug > notes, then most
// recently added. status optionally filters first.
func (s *Store) SearchGameBacklog(ctx context.Context, query, status string, limit int) ([]GameBacklogRow, error) {
	q := strings.TrimSpace(query)
	if q == "" {
		return nil, fmt.Errorf("search game_backlog: query is required")
	}
	if status != "" && !ValidGameBacklogStatus(status) {
		return nil, fmt.Errorf("search game_backlog: unknown status %q", status)
	}
	if limit <= 0 {
		limit = defaultGameBacklogListLimit
	}

	// Escape LIKE wildcards in the user query so % and _ match literally.
	esc := strings.NewReplacer(`\`, `\\`, "%", `\%`, "_", `\_`)
	pattern := "%" + esc.Replace(q) + "%"

	querySQL := gameBacklogSelectColumns + ` WHERE 1=1`
	var args []any
	if status != "" {
		querySQL += ` AND status = ?`
		args = append(args, status)
	}
	querySQL += ` AND (
		title LIKE ? ESCAPE '\'
		OR slug LIKE ? ESCAPE '\'
		OR notes LIKE ? ESCAPE '\'
	)
	ORDER BY (CASE
		WHEN title LIKE ? ESCAPE '\' THEN 3
		WHEN slug LIKE ? ESCAPE '\' THEN 2
		WHEN notes LIKE ? ESCAPE '\' THEN 1
		ELSE 0 END) DESC, added_at DESC
	LIMIT ?`
	args = append(args, pattern, pattern, pattern, pattern, pattern, pattern, limit)

	rows, err := s.db.QueryContext(ctx, querySQL, args...)
	if err != nil {
		return nil, fmt.Errorf("search game_backlog: %w", err)
	}
	defer rows.Close()
	out := []GameBacklogRow{}
	for rows.Next() {
		r, err := scanGameBacklogRow(rows)
		if err != nil {
			return nil, fmt.Errorf("scan game_backlog row: %w", err)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}
