// Copyright 2026 bleighk. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press).

package store

import (
	"context"
	"path/filepath"
	"strings"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

func openTestGameBacklogStore(t *testing.T) *Store {
	t.Helper()
	dbPath := filepath.Join(t.TempDir(), "game-backlog.db")
	s, err := OpenWithContext(context.Background(), dbPath)
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	t.Cleanup(func() { s.Close() })
	return s
}

func countGameBacklogRows(t *testing.T, s *Store) int {
	t.Helper()
	var n int
	if err := s.DB().QueryRow(`SELECT COUNT(*) FROM game_backlog`).Scan(&n); err != nil {
		t.Fatalf("count game_backlog: %v", err)
	}
	return n
}

func isRFC3339UTC(s string) bool {
	if _, err := time.Parse(time.RFC3339, s); err != nil {
		return false
	}
	return strings.HasSuffix(s, "Z") || strings.Contains(s, "+00:00")
}

func TestGameBacklogTableAndIndexesCreated(t *testing.T) {
	t.Parallel()
	s := openTestGameBacklogStore(t)

	var table string
	if err := s.DB().QueryRow(
		`SELECT name FROM sqlite_master WHERE type='table' AND name='game_backlog'`).Scan(&table); err != nil {
		t.Fatalf("game_backlog table missing after open: %v", err)
	}
	for _, idx := range []string{"idx_game_backlog_status", "idx_game_backlog_added_at"} {
		var name string
		if err := s.DB().QueryRow(
			`SELECT name FROM sqlite_master WHERE type='index' AND name=?`, idx).Scan(&name); err != nil {
			t.Fatalf("index %s missing after open: %v", idx, err)
		}
	}
}

func TestUpsertGameBacklog_InsertThenUpdateNoDuplicate(t *testing.T) {
	t.Parallel()
	s := openTestGameBacklogStore(t)
	ctx := context.Background()

	row, inserted, err := s.UpsertGameBacklog(ctx, GameBacklogInput{
		RawgID: 10394, Title: "Hollow Knight", Slug: "hollow-knight",
		Status: GameBacklogStatusBacklog, Notes: "weekly pick",
	})
	if err != nil {
		t.Fatalf("insert: %v", err)
	}
	if !inserted {
		t.Fatalf("first upsert should insert, got inserted=false")
	}
	if !isRFC3339UTC(row.AddedAt) {
		t.Fatalf("added_at not RFC3339 UTC: %q", row.AddedAt)
	}
	if row.FinishedAt != "" {
		t.Fatalf("fresh backlog row should have empty finished_at, got %q", row.FinishedAt)
	}

	// Upsert same id with different tracking fields: one row, updated in
	// place, added_at preserved.
	row2, inserted2, err := s.UpsertGameBacklog(ctx, GameBacklogInput{
		RawgID: 10394, Title: "Hollow Knight", Slug: "hollow-knight",
		Status: GameBacklogStatusInProgress, Hours: 4.5,
	})
	if err != nil {
		t.Fatalf("update upsert: %v", err)
	}
	if inserted2 {
		t.Fatalf("second upsert should update, not insert")
	}
	if row2.AddedAt != row.AddedAt {
		t.Fatalf("upsert rewrote added_at: %q vs %q", row2.AddedAt, row.AddedAt)
	}
	if row2.Status != GameBacklogStatusInProgress || row2.Hours != 4.5 {
		t.Fatalf("upsert did not apply fields: %+v", row2)
	}
	if got := countGameBacklogRows(t, s); got != 1 {
		t.Fatalf("duplicate row after upsert: %d rows", got)
	}
}

func TestUpsertGameBacklog_StatusFlipSetsAndClearsFinishedAt(t *testing.T) {
	t.Parallel()
	s := openTestGameBacklogStore(t)
	ctx := context.Background()

	_, _, err := s.UpsertGameBacklog(ctx, GameBacklogInput{
		RawgID: 58175, Title: "God of War", Slug: "god-of-war",
		Status: GameBacklogStatusBacklog,
	})
	if err != nil {
		t.Fatalf("insert: %v", err)
	}

	finished, ok, err := s.SetGameBacklogStatus(ctx, 58175, GameBacklogStatusFinished)
	if err != nil || !ok {
		t.Fatalf("flip to finished: ok=%v err=%v", ok, err)
	}
	if finished.FinishedAt == "" {
		t.Fatalf("finished_at not stamped on flip to finished")
	}
	if !isRFC3339UTC(finished.FinishedAt) {
		t.Fatalf("finished_at not RFC3339 UTC: %q", finished.FinishedAt)
	}

	resumed, ok, err := s.SetGameBacklogStatus(ctx, 58175, GameBacklogStatusInProgress)
	if err != nil || !ok {
		t.Fatalf("flip away from finished: ok=%v err=%v", ok, err)
	}
	if resumed.FinishedAt != "" {
		t.Fatalf("finished_at not cleared when leaving finished: %q", resumed.FinishedAt)
	}

	// Re-entering finished re-stamps (a second playthrough finish date).
	again, _, err := s.SetGameBacklogStatus(ctx, 58175, GameBacklogStatusFinished)
	if err != nil {
		t.Fatalf("re-finish: %v", err)
	}
	if again.FinishedAt == "" || !isRFC3339UTC(again.FinishedAt) {
		t.Fatalf("finished_at not re-stamped: %q", again.FinishedAt)
	}
}

func TestSetGameBacklogStatus_UnknownStatusRejected(t *testing.T) {
	t.Parallel()
	s := openTestGameBacklogStore(t)
	ctx := context.Background()

	if _, _, err := s.SetGameBacklogStatus(ctx, 1, "wishlist"); err == nil {
		t.Fatalf("expected error for unknown status")
	}
	if _, ok, err := s.SetGameBacklogStatus(ctx, 999, GameBacklogStatusFinished); err != nil || ok {
		t.Fatalf("missing id should be ok=false with nil error, got ok=%v err=%v", ok, err)
	}
}

func TestSetGameBacklogHours_UpdatesPlaytime(t *testing.T) {
	t.Parallel()
	s := openTestGameBacklogStore(t)
	ctx := context.Background()

	if _, _, err := s.UpsertGameBacklog(ctx, GameBacklogInput{
		RawgID: 8964, Title: "Yakuza 0", Slug: "yakuza-0",
	}); err != nil {
		t.Fatalf("insert: %v", err)
	}
	row, ok, err := s.SetGameBacklogHours(ctx, 8964, 12.25)
	if err != nil || !ok {
		t.Fatalf("set hours: ok=%v err=%v", ok, err)
	}
	if row.Hours != 12.25 {
		t.Fatalf("hours not updated: %v", row.Hours)
	}
	if _, _, err := s.SetGameBacklogHours(ctx, 8964, -1); err == nil {
		t.Fatalf("negative hours should be rejected")
	}
	if _, ok, err := s.SetGameBacklogHours(ctx, 999, 1); err != nil || ok {
		t.Fatalf("missing id should be ok=false with nil error, got ok=%v err=%v", ok, err)
	}
}

func TestRemoveGameBacklog_DeletesAndReports(t *testing.T) {
	t.Parallel()
	s := openTestGameBacklogStore(t)
	ctx := context.Background()

	if _, _, err := s.UpsertGameBacklog(ctx, GameBacklogInput{
		RawgID: 10394, Title: "Hollow Knight", Slug: "hollow-knight",
	}); err != nil {
		t.Fatalf("insert: %v", err)
	}
	removed, ok, err := s.RemoveGameBacklog(ctx, 10394)
	if err != nil || !ok {
		t.Fatalf("remove: ok=%v err=%v", ok, err)
	}
	if removed.Title != "Hollow Knight" {
		t.Fatalf("removed row should echo the entry, got %+v", removed)
	}
	if got := countGameBacklogRows(t, s); got != 0 {
		t.Fatalf("row not deleted: %d rows", got)
	}
	if _, ok, _ := s.RemoveGameBacklog(ctx, 10394); ok {
		t.Fatalf("removing a missing id should report ok=false")
	}
}

func TestListAndSearchGameBacklog_FilterSortRank(t *testing.T) {
	t.Parallel()
	s := openTestGameBacklogStore(t)
	ctx := context.Background()

	seed := []GameBacklogInput{
		{RawgID: 1, Title: "Hollow Knight", Slug: "hollow-knight"},
		{RawgID: 2, Title: "Hollow Knight: Silksong", Slug: "hollow-knight-silksong", Notes: "demo was great"},
		{RawgID: 3, Title: "Yakuza 0", Slug: "yakuza-0", Status: GameBacklogStatusFinished, Hours: 90},
		{RawgID: 4, Title: "Iconoclasts", Slug: "iconoclasts", Notes: "metroidvania like Hollow Knight"},
	}
	for _, in := range seed {
		if _, _, err := s.UpsertGameBacklog(ctx, in); err != nil {
			t.Fatalf("seed %d: %v", in.RawgID, err)
		}
	}

	all, err := s.ListGameBacklog(ctx, ListGameBacklogFilter{})
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	if len(all) != 4 {
		t.Fatalf("list should return 4 rows, got %d", len(all))
	}

	finished, err := s.ListGameBacklog(ctx, ListGameBacklogFilter{Status: GameBacklogStatusFinished})
	if err != nil || len(finished) != 1 || finished[0].RawgID != 3 {
		t.Fatalf("status filter failed: rows=%d err=%v", len(finished), err)
	}

	byTitle, err := s.ListGameBacklog(ctx, ListGameBacklogFilter{Sort: "title"})
	if err != nil {
		t.Fatalf("list sorted by title: %v", err)
	}
	if byTitle[0].Title != "Hollow Knight" {
		t.Fatalf("title sort failed: first=%q", byTitle[0].Title)
	}

	hits, err := s.SearchGameBacklog(ctx, "Hollow", "", 10)
	if err != nil {
		t.Fatalf("search: %v", err)
	}
	if len(hits) != 3 {
		t.Fatalf("search should match 3 rows, got %d", len(hits))
	}
	// Title matches (rows 1, 2) must outrank the notes-only match (row 4);
	// relative order within the title tier is added_at DESC and may tie at
	// second granularity, so only assert tier ordering.
	if hits[0].RawgID != 1 && hits[0].RawgID != 2 {
		t.Fatalf("title match should rank first, got rawg_id=%d", hits[0].RawgID)
	}
	if hits[1].RawgID != 1 && hits[1].RawgID != 2 {
		t.Fatalf("both title matches should rank above notes match, got rawg_id=%d", hits[1].RawgID)
	}
	if hits[2].RawgID != 4 {
		t.Fatalf("notes-only match should rank last, got rawg_id=%d", hits[2].RawgID)
	}

	notesOnly, err := s.SearchGameBacklog(ctx, "demo", "", 10)
	if err != nil || len(notesOnly) != 1 || notesOnly[0].RawgID != 2 {
		t.Fatalf("notes search failed: rows=%d err=%v", len(notesOnly), err)
	}

	escaped, err := s.SearchGameBacklog(ctx, "100%", "", 10)
	if err != nil || len(escaped) != 0 {
		t.Fatalf("LIKE wildcards in query must be literal, got rows=%d err=%v", len(escaped), err)
	}
}
